# Generated by Django 5.2.5 on 2025-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieID', models.CharField(max_length=20, unique=True)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(blank=True, max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100)),
                ('DirectorName', models.CharField(blank=True, max_length=100)),
                ('MovieGenre', models.CharField(choices=[('COM', 'Comedy'), ('ROM', 'Romance'), ('ACT', 'Action'), ('DRM', 'Drama'), ('HOR', 'Horror'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
